### ISSUE TITLE
Function interfaces of buffers

### ISSUE THREAD

**Issue by xor-gate** [ludocode/mpack#10]
I would like to suggest all functions/buffers should have the following prototypes:
writeable buffers: `void *buffer` or `void *data`
read only buffers:  `const void *buffer` or `const void *data` interface instead of char *. This maps directly to POSIX (like) APIs which directly use buffers. Because the size is given the void * size is known.

Maybe keep in mind constant pointers and pointers to constants:
http://www.codeguru.com/cpp/cpp/cpp_mfc/general/article.php/c6967/Constant-Pointers-and-Pointers-to-Constants.htm

Let me know what you think.

**Comment by ludocode** [comment]
Sorry for the long delay :) I spent a long time thinking about this issue.

It is true that `void*` is used for byte buffers throughout libc and POSIX. For libc, memory functions like `memcpy()` and file functions like `fread()` use `void*`. Other POSIX APIs like BSD sockets also use `void*`, such as `send()` and `recv()`. But I think that the convention in more modern APIs has changed.

[RapidJSON](http://rapidjson.org/md_doc_stream.html#StringStream) for example uses `const char*` for read-only buffers and `char*` for writeable buffers (at least, the concrete types do; a lot of is is templated on a character type, but I think it still requires a concrete character type, not `void`.) The reference [MsgPack C](https://github.com/msgpack/msgpack-c) implementation also uses `char*`, not `void*`. [YAJL](http://lloyd.github.io/yajl/yajl-2.1.0/yajl__gen_8h.html#a1060585da6ccce2bcf6d4820035e7b79) is another example that uses `const char*` and `size_t` (when it doesn't rely on null-termination.) (Many other parsers like Protocol Buffers are C++-only, so they use e.g. `std::string` or `std::vector<char>`.)

Some other modern C libraries do continue to use `void*`. [ENet](http://enet.bespin.org/group__Packet.html#gaac61b251aebbf9f5e5e313eca51339ea) is an example. However I think that part of the purpose here of taking `void*` instead of `char*` is that the packet may actually be aliased to a struct. This is a somewhat older style of networking, where struct padding is explicitly controlled and the various data fields are patched up with `htons()` and friends. This allows a struct to be essentially `memcpy()`'d into a packet and transmitted somewhat portably from one machine to another rather than having to serialize it. I very much hope that this form of networking dies out, and that efficient serialization libraries like MPack and FlatBuffers are the ones that kill it.

So I think that there are lots of reasons to prefer `char*` over `void*` in an API, and I think using `void*` would be misleading. With `char*` it is clear that the data should be just a chunk of bytes, and not some pointer-to-struct, array of `wchar_t`, or so on that was cast to a `void*`. It's also more convenient. The data is going to be parsed byte by byte anyway, so it might as well already be in a `char*`.

Anyway thanks for the input. I'm definitely interested in reading more about the `void*` vs. `char*` debate if you have more info.
