### ISSUE TITLE
scan-build warning with mpack_test

### ISSUE THREAD

**Issue by rikvdh** [ludocode/mpack#14]
[ 58%] Building C object 3rdparty/mpack/test/CMakeFiles/mpack_test.dir/__/src/mpack/mpack.c.o
../3rdparty/mpack/src/mpack/mpack.c:181:21: warning: Call to 'malloc' has an allocation size of 0 bytes
    void* new_ptr = malloc(new_size);
                    ^~~~~~~~~~~~~~~~
1 warning generated.

It is also in the travis output.
https://travis-ci.org/ludocode/mpack/jobs/77627638#L161

The odd thing is, it doesn't generate no report on this.

**Comment by ludocode** [comment]
Yeah I noticed that one a few weeks ago. It's weird because I'm calling scan-build with --status-bugs on Travis, but it still doesn't error, even though other scan-build warnings have caused the build to fail before. It also only happens in amalgamated builds, so it's doing some sort of analysis across files. I wasn't able to immediately figure out why it's happening, and I'm pretty sure it's safe, but I should still fix the warning. I also had a lot of trouble reproducing it locally (it doesn't happen on my local dev environment, but it does happen in one of my VMs) so it's hard to debug.

**Comment by rikvdh** [comment]
Fixed with PR #16
