### ISSUE TITLE
Integrate code-coverage analysis

### ISSUE THREAD

**Issue by rikvdh** [ludocode/mpack#18]
Perhaps it is a good idea to integrate https://coveralls.io/, I believe it gives you a badge (like Travis-CI) with your coverage and allows you to monitor the actual coverage of your tests.

**Comment by ludocode** [comment]
Coveralls.io is now supported on develop. It measures the code coverage of the default non-amalgamated debug build with all features under GCC. You can see the (poor) results here: https://coveralls.io/github/ludocode/mpack

The README badge has been added on develop, but unfortunately it's being incorrectly cached by GitHub. It seems to be somehow related to this: https://github.com/github/markup/issues/224

It might be because the coverage was originally unknown when I loaded the page, or because I was testing the README through grip, so hopefully it will fix itself. It might also be an http/https related issue, so if it stays broken I'll try changing it.

**Comment by ludocode** [comment]
The badge looks correct now: https://github.com/ludocode/mpack/tree/develop

I'll keep an eye on it to make sure it's updating correctly.
