### ISSUE TITLE
Static analysis malloc call with size 0

### ISSUE THREAD

**Issue by xor-gate** [ludocode/mpack#21]
Our code with continues integration has scan-build (clang-analyzer) and found with v0.6 the following bug:

Unix API	Undefined allocation of 0 bytes (CERT MEM04-C; CWE-131)	/3rdparty/mpack/src/mpack/mpack.c	3	Call to 'malloc' has an allocation size of 0 bytes

```
2358	#ifdef MPACK_MALLOC
2359	void* mpack_expect_array_alloc_impl(mpack_reader_t* reader, size_t element_size, uint32_t max_count, size_t* out_count) {
2360	    size_t count = *out_count = mpack_expect_array(reader);
2361	    if (mpack_reader_error(reader))
1
Taking false branch	
→
2362	        return NULL;
2363	    if (count > max_count) {
2
←
Taking false branch	
→
2364	        mpack_reader_flag_error(reader, mpack_error_type);
2365	        return NULL;
2366	    }
2367	    void* p = MPACK_MALLOC(element_size * count);
3
←
Within the expansion of the macro 'MPACK_MALLOC':
a
Call to 'malloc' has an allocation size of 0 bytes

2368	    if (p == NULL)
2369	        mpack_reader_flag_error(reader, mpack_error_memory);
2370	    return p;
2371	}
2372	#endif
```

**Comment by ludocode** [comment]
Fixed on develop. Sorry for the delay; I just got back from vacation.

Unfortunately there aren't any unit tests for this function yet. More tests will be written soon.

**Comment by xor-gate** [comment]
No problem, i did notice it and wanted to let you know. Maybe compiling mpack with clang/clang-analyzer and extra/more strict options would be good to have it covered in the future.

**Comment by ludocode** [comment]
MPack is actually built with `scan-build --status-bugs` on Travis-CI on every commit, in both standard and amalgamation modes. The build fails if any code analysis issues appear, but for some reason this error wasn't showing up. Maybe Travis has an older version of clang-analyzer, or maybe it was ignoring it because this function has no unit tests.

See the scan-build tests here for the previous build before this fix: https://travis-ci.org/ludocode/mpack/builds/83479015

**Comment by xor-gate** [comment]
Yeah I see, we are using scan-build-3.5 which reports this error. The fix looks very good and is very gracefull :-). We will integrate when a new release done and I will close for now.

Thanks for your effort,
Jerry
