### ISSUE TITLE
Non-negative integers are always written as unsigned

### ISSUE THREAD

**Issue by dwlnetnl** [ludocode/mpack#33]
In a project I'm writing in sometimes negative and sometimes non-negative integers. The current implementation always writes a non-negative integer as an unsigned integer. The consequence of this is cumbersome decoding logic: try to decode the value as an uint and if that fails decode it as an int.

As far as I can see is the spec not explicit about changing the type of a signed into an unsigned integer. However, the spec states indeed that the smallest representation should be used whenever that's possible. When I interpret the spec, I consider signed and unsigned integers as separate non-interchangeable types. So for me an non-negative integer can't be 'optimized' into an unsigned integer that maybe is smaller to represent.

I look forward to your reaction. Maybe it can be an header #define in mpack-config.h?

**Comment by ludocode** [comment]
As far as I know, all C/C++ implementations of MessagePack discard the signedness of integers when writing. (You can confirm this in the [speed benchmark hash results](https://github.com/ludocode/schemaless-benchmarks/blob/master/full-results-extended.md#write-test-1); the hash value of "b4ac134d" is the same for msgpack-c, MPack and CMP, meaning they produced the identical ~250kb of MessagePack.)

The [protocol clarifications](https://github.com/ludocode/mpack/blob/master/docs/protocol.md#integer-signedness) document describes how and why MPack discards signedness. Basically, storing the number 1 as a signed int would require two bytes, since there are no signed positive fixints. So although the specification is unclear, the intent seems to be to discard signedness, and the reference implementation discards signedness.

So I'm not likely to implement this any time soon, but you could implement it yourself fairly easily by modifying `mpack_write_i8()`, `mpack_write_i16()`, `mpack_write_i32()` and `mpack_write_i64()` to only output signed numbers (and only use fixint for [-31,-1].) You wouldn't have to change anything in the reader or node APIs since tags and node types reflect the signedness of the serialized type, but beware that the node and expect helpers (e.g. `mpack_expect_int()` or `mpack_node_int()`) will convert between signedness.

**Comment by ludocode** [comment]
And as I'm reading this I just realized that protocol document has a bug :) The number 231 as signed should be `D1 00 E7`, so 231 is not an appropriate example for an int of equivalent length representation in both signed and unsigned... Will fix.

**Comment by dwlnetnl** [comment]
Well I see. No problem, than it's an 'issue' during decoding int's to detect if it's encoded as an unsigned int.
