### ISSUE TITLE
Integration of optional C11 write and read

### ISSUE THREAD

**Issue by xor-gate** [ludocode/mpack#34]
As we talked before, I would like to contribute an optional extension to mpack to have primitive values (messagepack) easily serialized and deserialized with the C11 _Generic selection. The compiler can then select the according function at compile time instead of the programmer itself.
This could add to following functions to the API (defines):

```c
mpack_write(mpack_writer_t writer, <generic selected type, uint8_t, uint16_t etcetera>);
mpack_read(mpack_writer_t reader, <generic selected type, uint8_t, uint16_t etcetera>);
```

Let me know what you think then I will start integration of current code as pull request. If we can not easily detect this C11 feature we could make it explict enable/disable this feature with a mpack-config.h define e.g: `MPACK_C11_EXTENSION`.

**Comment by ludocode** [comment]
I think this is a good idea. An `mpack_write()` macro for primitives that uses `_Generic` to dispatch based on its argument would feel natural. There's an easy C++ implementation as well which is just to use overloaded inline functions.

For the reader macro, I'm guessing you would want something like `mpack_expect()` that takes a pointer to the output, since you can't dispatch based on return type. For example `mpack_expect(reader, &output)` which is dispatched to one of the expect functions based on the type of the output. Is this sort of what you were thinking?

In any case, if you want to contribute these, you can create a PR against develop and add them to the bottom of `mpack-writer.h` and whichever file is appropriate for the reader (`mpack-expect.h` or `mpack-reader.h` depending on what you implement.) You could detect support for this automatically based on `__STDC_VERSION__`, defining something like `MPACK_HAS_GENERIC` under `if __STDC_VERSION__ >= 201112L`, so there shouldn't be a need for anything in the config. (The same check is currently used already in `mpack-platform.h` for `_Static_assert`.) If you don't want to write the C++ fallbacks I can take care of that part; some of it may already be done in the C++ bindings branch.

**Comment by xor-gate** [comment]
For the reader we need some more thinking. Do you have an idea how the simple C datatype generic reader would look like? Probably we would need to peek and set the error when the application tries to read e.g a uint8_t but a uint16_t is fetched from the stream.

**Comment by xor-gate** [comment]
I think for now we can close this. Because there is no real generic way to have a generic reader, because reading composite types (structs) is a lot more pain than first expected, in C/C++ . Also reading is mostly application specific. A DSL generated deserializer code can only solve this problem, and is application specific. The generic reader is now awesome :+1:
