### ISSUE TITLE
mpack_write_native could be public when tracking mode is enabled

### ISSUE THREAD

**Issue by xor-gate** [ludocode/mpack#39]
Currently I'm implementing a serializer where a messagepack msg is crafted in two pieces. 
* I write first an map into a buffer, e.g error object
* I write message header into a second buffer

Then I want to write the error object buffer into the message header second buffer:

error object (json presentation):
```
{ 
   "descr" : "This is a really bad error",
   "code" : 1337
}
```

header + error object buffer:
```
{
   "version" : 1
   "reply" : "foobar"
   "error" :  < data of error object buffer > 
}
```

I first tried using `mpack_write_bytes` and this hit a breakpoint because for debug builds I have tracking enabled. So basicly I need a "untracked" byte writer where bounds are checked when I'm still building with tracking enabled.

Feel free to ask if something is not clear.

**Comment by xor-gate** [comment]
I think there should be a more elegant solution because I tried to copy the `mpack_memcpy` and increment the `writer.used` field but then the tracking still works like expected and emits and breakpoint error there are 2 elements left.

**Comment by ludocode** [comment]
To fix the tracking after writing an object "manually", you need to call `mpack_writer_track_element()`. This lets it know that an element has been written. The tracking otherwise doesn't look at `mpack_write_native()`.

I've wanted support for this sort of thing as well, for doing almost exactly what you are doing. I have a UDP network packet as a MessagePack object with header info like you have there, and then the application-level data is just a portion of the message after the header. It makes for a much nicer design if the application can write its own MessagePack data without any header, and then the networking code can compose a message with header by just writing the outer MessagePack bytes into it at the right spot.

Something like this might work:

```C
// writes a pre-encoded messagepack object
mpack_write_object_bytes(mpack_writer_t* writer, const char* data, size_t bytes) {
    mpack_writer_track_element(writer);
    mpack_write_native(writer, data, bytes);
}
```

**Comment by xor-gate** [comment]
This works like a charm, i have locally patched my mpack amalgamated package for now :+1:
