### ISSUE TITLE
New release merge from develop

### ISSUE THREAD

**Issue by xor-gate** [ludocode/mpack#41]
Hi @ludocode,

Are there any plans to have a official release tagged and amalgamated? Last release was 3 months ago and some things are more awesome then before :+).
I'm not sure but maybe you need to bump the minor version number because the api has been extended.

I'm not sure you want to get some new features or fixes into the new release, that's why i'm asking. I tracked your public activity and saw you where very busy with the msgpack-tools.

Kind regards,
Jerry

**Comment by ludocode** [comment]
Yep, sorry. I've been meaning to put together a new release for some time. I wanted to add an `mpack_node_enum()` counterpart to match the new `mpack_expect_enum()` first, but other than that there isn't much else that needs to be done for the next release.

I also want to get started on some new features which will slightly change some APIs, and I should really do a point release before then to minimize the changes. I want to add option flags that will include a compatibility mode to write old-style MessagePack, since it still seems to be needed unfortunately. And then I want to get started on a cooperative stream mode for the tree parser to do non-blocking RPC over a socket connection. This is really the only major feature that the reference implementation has that MPack still does not have, and intend to use it soon.

Anyway I'll probably get around to it this weekend. In the meantime, I separated out the amalgamate.sh script from the package.sh script under tools/ a while back, so it's a lot easier to assemble yourself the amalgamated source if you need.

**Comment by xor-gate** [comment]
Okay good, this sounds like a plan :+1:

**Comment by xor-gate** [comment]
Thanks for the quick response, looks good to me.
