### ISSUE TITLE
Reader documentation?

### ISSUE THREAD

**Issue by csstup** [ludocode/mpack#44]
There is no documentation/example on using the reader/expect API.   Only the Reader Node API.

Could this be added please?

**Comment by ludocode** [comment]
A guide for using the Expect API exists under Pages. [It's available here](http://ludocode.github.io/mpack/md_docs_expect.html).

There isn't a guide for just the dynamic Reader API unfortunately. If you want to use it, follow the Expect guide to initialize a reader, and instead of calling the expect functions, call `mpack_read_tag()`. You'll get back an [`mpack_tag_t`](http://ludocode.github.io/mpack/group__common.html#structmpack__tag__t) that contains the dynamic type of the object read. From there, call `mpack_read_bytes()` and friends to read strings, and don't forget to call the `mpack_done_*()` functions after any compound type.

The rest of the Reader and Expect documentation is [here](http://ludocode.github.io/mpack/modules.html).

**Comment by xor-gate** [comment]
@ludocode this is almost the same as #45 should I mockup a example with some documentation?

**Comment by ludocode** [comment]
Thanks for the offer of help, but it's not necessary anymore. I've finally put together guides for the [Reader API](https://github.com/ludocode/mpack/blob/develop/docs/reader.md) and [Node API](https://github.com/ludocode/mpack/blob/develop/docs/node.md). They'll be added to the Doxygen docs as soon as I generate it.
