### ISSUE TITLE
On-the-fly deserialization/parsing

### ISSUE THREAD

**Issue by pozzugno** [ludocode/mpack#45]
I'm new to serialization formats and I decided to start with MessagePack. I'd like to use it in an embedded project with limited resources of memory.

I'm going to deserialize/parse a long message, but I'd like to make it "on-the-fly", node by node.

I understood I have to use mpack_tree_parse() that parses all the message and creates a dynamically typed tree in memory. But I don't have the memory space for the full tree of the message.

Is it possible to parse the message node by node on-the-fly?

**Comment by ludocode** [comment]
Yep, you can use the reader/expect API for this instead of the node/tree API. Documentation for the expect API is here:

https://ludocode.github.io/mpack/md_docs_expect.html

For dynamic type parsing, the setup is the same. You just use `mpack_read_tag()` and switch on the type instead of calling the expect functions. Documentation for the reader and expect API is here:

https://ludocode.github.io/mpack/group__reader.html
https://ludocode.github.io/mpack/group__expect.html

**Comment by xor-gate** [comment]
@pozzugno i'm using the mpack reader in this way on a embedded microcontroller target. Do you still need some help or an example? If you want I can help out.

**Comment by ludocode** [comment]
This is now fixed. I put together guides for the [Reader API](https://github.com/ludocode/mpack/blob/develop/docs/reader.md) and [Node API](https://github.com/ludocode/mpack/blob/develop/docs/node.md).
