### ISSUE TITLE
Are the amalgamation releases simple aggration of src/mpack

### ISSUE THREAD

**Issue by ghost** [ludocode/mpack#60]
Will I get the same result as the amalgamated files if I clone the repository and copy all the files from `src/mpack` into where I would have copies the amalgamated `mpack.c` and `mpack.h`?

**Comment by ludocode** [comment]
Yes, you can include the library as-is instead of using the amalgamation. In fact this is how I use it in my own projects: I just have mpack as a git submodule and build all the .c files. The library might be better optimized when amalgamated, that's about it.

Just note the one weirdness right now which is that `mpack-platform.h` includes `mpack-config.h.sample` to set defaults. I'm not sure how IDEs will handle this. I should probably rename it to a normal `.h` file.

**Comment by ghost** [comment]
Thanks.
